### ISSUE TITLE
The choice of head_idx

### ISSUE THREAD

**Issue by kwea123** [ShirAmir/dino-vit-features#1]
https://github.com/ShirAmir/dino-vit-features/blob/79c1289b5a83960b85ca8e268bc569f48975fddb/extractor.py#L313

Is there any reason why you choose these heads?

**Comment by ShirAmir** [comment]
We found that heads 1 and 3 attend to background information in ViT-S, so we decided to disregard them for saliency map creation. The method still works comparably well when using all heads, at the cost of adjusting some parameters.
