### ISSUE TITLE
Supervised ViT Checkpoint

### ISSUE THREAD

**Issue by mhamilton723** [ShirAmir/dino-vit-features#3]
Hi, thanks for this great repo! Could you by chance point me in the direction of the "Supervised ViT" described in Figure 3?

**Comment by ShirAmir** [comment]
Hi!
As mentioned in the supplementary material, we used the supervised ViT `vit_small_patch16_224` from the [timm](https://github.com/rwightman/pytorch-image-models) repository to generate Figure 3.

Our code supports running with different ViTs trained in a supervised manner / with DINO. Just specify `--model_type <model_type>` with any of the following options:
```
[dino_vits8 | dino_vits16 | dino_vitb8 | dino_vitb16 | vit_small_patch8_224 |  vit_small_patch16_224 | vit_base_patch8_224 | vit_base_patch16_224]
```

Also, we have just uploaded code to generate PCA to a collection of images as done in Figure 3. You can find it in `pca.py`.
