### ISSUE TITLE
Evaluation subsets and code for fair comparison.

### ISSUE THREAD

**Issue by saksham-s** [ShirAmir/dino-vit-features#5]
Hi,

Is it possible to share the evaluation splits and code for fair comparison?

Thanks

**Comment by ShirAmir** [comment]
Hi,
We applied the methods on the datasets mentioned in the paper. The methods work in inference time, and do not involve any training. Do you have a question about any dataset / application in particular?

**Comment by saksham-s** [comment]
Specifically, I saw that this [https://dino-vit-features.github.io/sm/assets/pascalco/results.html](https://dino-vit-features.github.io/sm/assets/pascalco/results.html) contains 20 sets from the Pascal-CO dataset. Where can I find the other 20? Thanks :)

**Comment by ShirAmir** [comment]
The Pascal-CO dataset can be currently found in [this link](https://drive.google.com/file/d/1m_KQEoa7I-Ieg8pGbu7ceGnY3vQNEFSd/view?usp=sharing).

**Comment by saksham-s** [comment]
Thanks!
