### ISSUE TITLE
Use of the previous KMeans instance

### ISSUE THREAD

**Issue by mateusz-politycki-wttech** [ShirAmir/dino-vit-features#7]
I wonder if using the previous KMeans instance at this point is intentional. I mean the part_algorithm was trained on normalized_all_fg_sampled_descriptors as opposed to common_part_algorithm, which is trained on normalized_all_common_sampled_descriptors.
https://github.com/ShirAmir/dino-vit-features/blob/4b023eca1ac0bd462a68fcd03ccbdcb5aed40cb1/part_cosegmentation.py#L273

**Comment by ShirAmir** [comment]
Hi @mateusz-politycki-wttech, thanks for pointing out the issue! it is indeed a bug.
it has been fixed and updated in the repo.

Due note that we recommend using the three stage version only on small sets.
